version: '3'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.server
    ports:
      - '8080:8080'
    environment:
      - DATABASE_URL=file:/data/dev.db
      - SESSION_SECRET=change_me
      - PORT=8080
      - FRONTEND_ORIGIN=http://localhost:5173
    volumes:
      - ./data:/data
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - '5173:80'
